# Generated by Django 3.0.4 on 2020-07-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(default='default.JPG', upload_to='img'),
        ),
    ]
