# Generated by Django 3.0.7 on 2020-07-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200703_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.IntegerField(default=456),
        ),
    ]
