# Generated by Django 3.0.4 on 2020-07-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pic',
            field=models.FileField(default='default.jpg', upload_to='img'),
        ),
    ]
